# Lab 09
## Complete the questions below in the space provided.

Import numpy for use in the program

Before starting, download the files chicken_weight.csv and chicken_data.csv.  The file chicken_weight.csv is a comma delimited file that stores the weights of a set of chickens and time, which is the time in days since their birth.  The file chicken_data.csv is a comma-delimited file that stores data for the same set of chickens in the same order.  The file chicken_data.csv includes the columns: chick, (an identifier for each chicken) and diet (value between 1 - 4).

In [123]:
import numpy as np 

Read the data in the comma-delimited file, chicken_weight.csv into a numpy array, weights

In [124]:
weightData = np.loadtxt('chicken_weight.csv', delimiter = ',')

Read the data in the comma-delimited file, chicken_data.csv into a numpy array, data

In [125]:
chickData = np.loadtxt('chicken_data.csv', delimiter = ',', skiprows = 1)

Merge the numpy arrays, weights and data into a two-dimensional numpy array, chicken_data.  The first column should store the weights, and the remaining columns should store the time (in days) from birth, the chicken identifier and the chicken diet (1 - 4).

In [126]:
chicken_data = np.hstack([weightData.T, chickData])

Display the mean weight and time for all chickens.

In [127]:
print("Mean weight:",np.mean(chicken_data[:,0]))
print("Mean time:",np.mean(chicken_data[:,1]))

Mean weight: 121.81833910034602
Mean time: 21.43598615916955


Display the data for the chick with the id 38.

In [128]:
index = np.where(chicken_data[:,2] == 38)
print("Data of the chick with id 38 is",chicken_data[index,:])

Data of the chick with id 38 is [[[ 41.   0.  38.   3.]
  [ 49.   4.  38.   3.]
  [ 61.   8.  38.   3.]
  [ 74.  12.  38.   3.]
  [ 98.  16.  38.   3.]
  [109.  20.  38.   3.]
  [128.  24.  38.   3.]
  [154.  28.  38.   3.]
  [192.  32.  38.   3.]
  [232.  36.  38.   3.]
  [280.  40.  38.   3.]
  [290.  42.  38.   3.]]]


Calculate and display the maximum chicken weight.

In [129]:
print("Maximum chicken weight is ",np.max(weightData[0,:]))

Maximum chicken weight is  373.0


Find and display the age (in days) of the chicken(s) with the maximum weight.

In [130]:
maxWeight = np.max(chicken_data[:,0])
a = chicken_data[chicken_data[:,0] == maxWeight]
print("Age of the chickens with maximum weight",a[:,1])

Age of the chickens with maximum weight [42.]


Extract an array containing the weight, time and id of all chickens with diet 4 and save to a file, diet_four_chickens.csv.

In [131]:
a = chicken_data[chicken_data[:,3] == 4]
np.savetxt("diet_four_chickens.csv.", a, fmt = "%.1f")